FROM node:16
# RUN mkdir -p /app
WORKDIR /usr/app

RUN npm install nodemon -g

COPY package*.json ./
RUN npm install
COPY . /usr/app/.
EXPOSE 3000
CMD ["nodemon", "app.js"]


# FROM node:boron
# RUN mkdir -p /usr/src/app
# WORKDIR /usr/src/app
# COPY package.json /usr/src/app/
# RUN npm install
# COPY . /usr/src/app
# EXPOSE 3000
# CMD ["npm","start"]